# Generated by Django 3.1.5 on 2021-01-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210122_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='KGS', max_length=3)),
                ('price_amount', models.DecimalField(decimal_places=2, default='5', max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
    ]
