# Generated by Django 3.1.5 on 2021-01-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210122_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
