# Generated by Django 3.1.5 on 2021-01-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210122_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default='5', max_digits=9),
        ),
    ]
