# Generated by Django 3.1.5 on 2021-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210122_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.CharField(default='KGS', max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
