# Generated by Django 3.1.5 on 2021-01-22 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210122_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost_amount',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
