# Generated by Django 3.1.5 on 2021-01-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210123_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cost_amount',
            field=models.IntegerField(default=0),
        ),
    ]
