# Generated by Django 3.1.5 on 2021-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210123_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='cost_amount',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.DateField(),
        ),
    ]
