# Generated by Django 3.1.5 on 2021-01-24 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210124_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date',
        ),
        migrations.AddField(
            model_name='books',
            name='adding_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
