# Generated by Django 3.1.5 on 2021-01-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210124_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='books_date',
            field=models.DateField(auto_now=True),
        ),
    ]
