# Generated by Django 3.1.5 on 2021-01-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210124_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='books_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
